quarkus.log.level=INFO
quarkus.log.min-level=INFO
quarkus.log.console.async.enabled=true

quarkus.shutdown.delay-enabled=true
quarkus.shutdown.delay=3
quarkus.http.root-path=/api/v1/history
quarkus.http.port=${HTTP_PORT:8080}

quarkus.grpc.server.port=9002
quarkus.rest-client.detail-filling-service.url=${DETAIL_FILLING_SERVICE_URL:http://localhost:9081}
quarkus.grpc.clients.training-service.host=${TRAINING_SERVICE_HOST:training-service}
quarkus.grpc.clients.training-service.port=${TRAINING_SERVICE_PORT:9001}

quarkus.datasource.db-kind=${DB_KIND:postgresql}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/history}
quarkus.datasource.username=${DB_USER:user}
quarkus.datasource.password=${DB_PASSWORD:pass}
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.datasource.jdbc.max-size=50

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=docs
quarkus.smallrye-openapi.path=openapi.yaml
quarkus.openapi.always-include=true