# Root logger configuration - Sets the default minimum level for all loggers
quarkus.log.level=ALL
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.http.port=${HTTP_PORT}
config.detail-filling-api/mp-rest/url=${DETAIL_FILLING_SERVICE_URL}
config.analysis-api/mp-rest/url=${ANALYSIS_SERVICE_URL}
