config:
  gcp:project: hellocloud-489215
  gcp:region: europe-west1
  scrimfinder:cluster_name: scrimfinder-dev
  scrimfinder:zone_suffix: "a"
  scrimfinder:repo_name: scrimfinder
  scrimfinder:node_machine_type: e2-standard-4
  scrimfinder:node_count: "1"
  scrimfinder:min_nodes: "1"
  scrimfinder:max_nodes: "2"
  scrimfinder:disk_size_gb: "40"
  scrimfinder:enable_spot: "true"
  scrimfinder:gke_channel: REGULAR
  scrimfinder:master_cidr: "0.0.0.0/0"