package fc.ul.scrimfinder.util;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum Champion {
    AATROX("AATROX"),
    AHRI("AHRI"),
    AKALI("AKALI"),
    AKSHAN("AKSHAN"),
    ALISTAR("ALISTAR"),
    AMBESSA("AMBESSA"),
    AMUMU("AMUMU"),
    ANIVIA("ANIVIA"),
    ANNIE("ANNIE"),
    APHELIOS("APHELIOS"),
    ASHE("ASHE"),
    @JsonProperty("AURELION SOL")
    AURELION_SOL("AURELION SOL"),
    AURORA("AURORA"),
    AZIR("AZIR"),
    BARD("BARD"),
    @JsonProperty("BEL'VETH")
    BELVETH("BEL'VETH"),
    BLITZCRANK("BLITZCRANK"),
    BRAND("BRAND"),
    BRAUM("BRAUM"),
    BRIAR("BRIAR"),
    CAITLYN("CAITLYN"),
    CAMILLE("CAMILLE"),
    CASSIOPEIA("CASSIOPEIA"),
    @JsonProperty("CHO'GATH")
    CHOGATH("CHO'GATH"),
    CORKI("CORKI"),
    DARIUS("DARIUS"),
    DIANA("DIANA"),
    @JsonProperty("DR. MUNDO")
    DR_MUNDO("DR. MUNDO"),
    DRAVEN("DRAVEN"),
    EKKO("EKKO"),
    ELISE("ELISE"),
    EVELYNN("EVELYNN"),
    EZREAL("EZREAL"),
    FIDDLESTICKS("FIDDLESTICKS"),
    FIORA("FIORA"),
    FIZZ("FIZZ"),
    GALIO("GALIO"),
    GANGPLANK("GANGPLANK"),
    GAREN("GAREN"),
    GNAR("GNAR"),
    GRAGAS("GRAGAS"),
    GRAVES("GRAVES"),
    GWEN("GWEN"),
    HECARIM("HECARIM"),
    HEIMERDINGER("HEIMERDINGER"),
    HWEI("HWEI"),
    ILLAOI("ILLAOI"),
    IRELIA("IRELIA"),
    IVERN("IVERN"),
    JANNA("JANNA"),
    @JsonProperty("JARVAN IV")
    JARVAN_IV("JARVAN IV"),
    JAX("JAX"),
    JAYCE("JAYCE"),
    JHIN("JHIN"),
    JINX("JINX"),
    @JsonProperty("K'SANTE")
    KSANTE("K'SANTE"),
    @JsonProperty("KAI'SA")
    KAISA("KAI'SA"),
    KALISTA("KALISTA"),
    KARMA("KARMA"),
    KARTHUS("KARTHUS"),
    KASSADIN("KASSADIN"),
    KATARINA("KATARINA"),
    KAYLE("KAYLE"),
    KAYN("KAYN"),
    KENNEN("KENNEN"),
    @JsonProperty("KHA'ZIK")
    KHAZIX("KHA'ZIX"),
    KINDRED("KINDRED"),
    KLED("KLED"),
    @JsonProperty("KOG'MAW")
    KOGMAW("KOG'MAW"),
    LEBLANC("LEBLANC"),
    @JsonProperty("LEE SIN")
    LEE_SIN("LEE SIN"),
    LEONA("LEONA"),
    LILLIA("LILLIA"),
    LISSANDRA("LISSANDRA"),
    LUCIAN("LUCIAN"),
    LULU("LULU"),
    LUX("LUX"),
    MALPHITE("MALPHITE"),
    MALZAHAR("MALHAZAR"),
    MAOKAI("MAOKAI"),
    @JsonProperty("MASTER YI")
    MASTER_YI("MASTER YI"),
    MEL("MEL"),
    MILIO("MILIO"),
    @JsonProperty("MISS FORTUNE")
    MISS_FORTUNE("MISS FORTUNE"),
    MORDEKAISER("MORDEKAISER"),
    MORGANA("MORGANA"),
    NAAFIRI("NAAFIRI"),
    NAMI("NAMI"),
    NASUS("NASUS"),
    NAUTILUS("NAUTILUS"),
    NEEKO("NEEKO"),
    NIDALEE("NIDALEE"),
    NILAH("NILAH"),
    NOCTURNE("NOCTURNE"),
    @JsonProperty("NUNU & WILLUMP")
    NUNU_WILLUMP("NUNU & WILLUMP"),
    OLAF("OLAF"),
    ORIANNA("ORIANNA"),
    ORNN("ORNN"),
    PANTHEON("PANTHEON"),
    POPPY("POPPY"),
    PYKE("PYKE"),
    QIYANA("QIYANA"),
    QUINN("QUINN"),
    RAKAN("RAKAN"),
    RAMMUS("RAMMUS"),
    @JsonProperty("REK'SAI")
    REKSAI("REK'SAI"),
    RELL("RELL"),
    @JsonProperty("RENATA GLASC")
    RENATA_GLASC("RENATA GLASC"),
    RENEKTON("RENEKTON"),
    RENGAR("RENGAR"),
    RIVEN("RIVEN"),
    RUMBLE("RUMBLE"),
    RYZE("RYZE"),
    SAMIRA("SAMIRA"),
    SEJUANI("SEJUANI"),
    SENNA("SENNA"),
    SERAPHINE("SERAPHINE"),
    SETT("SETT"),
    SHACO("SHACO"),
    SHEN("SHEN"),
    SHYVANA("SHYVANA"),
    SINGED("SINGED"),
    SION("SION"),
    SIVIR("SIVIR"),
    SKARNER("SKARNER"),
    SMOLDER("SMOLDER"),
    SONA("SONA"),
    SORAKA("SORAKA"),
    SWAIN("SWAIN"),
    SYLAS("SYLAS"),
    SYNDRA("SYNDRA"),
    @JsonProperty("TAHM KENCH")
    TAHM_KENCH("TAHM KENCH"),
    TALIYAH("TALIYAH"),
    TALON("TALON"),
    TARIC("TARIC"),
    TEEMO("TEEMO"),
    THRESH("THRESH"),
    TRISTANA("TRISTANA"),
    TRUNDLE("TRUNDLE"),
    TRYNDAMERE("TRYNDAMERE"),
    TWISTED_FATE("TWISTED FATE"),
    TWITCH("TWITCH"),
    UDYR("UDYR"),
    URGOT("URGOT"),
    VARUS("VARUS"),
    VAYNE("VAYNE"),
    VEIGAR("VEIGAR"),
    @JsonProperty("VEL'KOZ")
    VELKOZ("VEL'KOZ"),
    VEX("VEX"),
    VI("VI"),
    VIEGO("VIEGO"),
    VIKTOR("VIKTOR"),
    VLADIMIR("VLADIMIR"),
    VOLIBEAR("VOLIBEAR"),
    WARWICK("WARWICK"),
    WUKONG("WUKONG"),
    XAYAH("XAYAH"),
    XERATH("XERATH"),
    @JsonProperty("XIN ZHAO")
    XIN_ZHAO("XIN ZHAO"),
    YASUO("YASUO"),
    YONE("YONE"),
    YORICK("YORICK"),
    YUNARA("YUNARA"),
    YUUMI("YUUMI"),
    ZAAHEN("ZAAHEN"),
    ZAC("ZAC"),
    ZED("ZED"),
    ZERI("ZERI"),
    ZIGGS("ZIGGS"),
    ZILEAN("ZILEAN"),
    ZOE("ZOE"),
    ZYRA("ZYRA");

    final String name;

    public static Champion fromChampionName(String name) {
        for (Champion c : values()) {
            if (c.name.equalsIgnoreCase(name)) {
                return c;
            }
        }
        return null;
    }
}
