apiVersion: v1
kind: Secret
metadata:
  name: scrimfinder-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  riot-api-key: {{ .Values.secrets.riotApiKey | quote }}
  db-user: {{ .Values.secrets.dbUser | quote }}
  db-password: {{ .Values.secrets.dbPassword | quote }}
  redis-password: {{ .Values.secrets.redisPassword | default "redispassword" | quote }}
  rabbitmq-user: {{ .Values.secrets.rabbitmqUser | default "user" | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmqPassword | default "rabbitmqpassword" | quote }}
  rabbitmq-erlang-cookie: {{ .Values.secrets.rabbitmqErlangCookie | default "erlangcookie" | quote }}
