# from https://oneuptime.com/blog/post/2026-02-26-argocd-csi-secrets-store-driver/view
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-scrimfinder
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-15"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  provider: gcp-csi-provider
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.global.projectID }}/secrets/riot-api-key/versions/latest"
        path: "riot-api-key"
      - resourceName: "projects/{{ .Values.global.projectID }}/secrets/db-user/versions/latest"
        path: "db-user"
      - resourceName: "projects/{{ .Values.global.projectID }}/secrets/db-password/versions/latest"
        path: "db-password"
      - resourceName: "projects/{{ .Values.global.projectID }}/secrets/redis-password/versions/latest"
        path: "redis-password"
      - resourceName: "projects/{{ .Values.global.projectID }}/secrets/rabbitmq-user/versions/latest"
        path: "rabbitmq-user"
      - resourceName: "projects/{{ .Values.global.projectID }}/secrets/rabbitmq-password/versions/latest"
        path: "rabbitmq-password"
      - resourceName: "projects/{{ .Values.global.projectID }}/secrets/rabbitmq-erlang-cookie/versions/latest"
        path: "rabbitmq-erlang-cookie"
  secretObjects:
    - secretName: scrimfinder-secrets
      type: Opaque
      data:
        - objectName: riot-api-key
          key: RIOT_API_KEY
        - objectName: db-user
          key: DB_USER
        - objectName: db-password
          key: DB_PASSWORD
        - objectName: redis-password
          key: REDIS_PASSWORD
        - objectName: rabbitmq-user
          key: RABBITMQ_USER
        - objectName: rabbitmq-password
          key: RABBITMQ_PASSWORD
        - objectName: rabbitmq-erlang-cookie
          key: RABBITMQ_ERLANG_COOKIE
