apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.secretsServiceAccountName | default "scrimfinder-secrets-reader" }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-16"
    iam.gke.io/gcp-service-account: "secrets-service-account@{{ .Values.global.projectID }}.iam.gserviceaccount.com"
