ranking-service-api/mp-rest/url=${RANKING_SERVICE_URL:http://localhost:8080}

quarkus.redis.hosts=${REDIS_URL:redis://localhost:6379}
quarkus.datasource.db-kind=${DB_KIND:postgresql}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/matchmaking}

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.http.port=${HTTP_PORT:8080}
quarkus.http.root-path=/api/v1/matchmaking

quarkus.grpc.clients.player-service.host=${PLAYER_FILLING_SVC_HOST:detail-filling-service}
quarkus.grpc.clients.player-service.port=${PLAYER_FILLING_SVC_PORT:9000}
quarkus.grpc.clients.player-service.plain-text=true

quarkus.grpc.clients.ranking-service.host=${RANKING_SVC_HOST:ranking-service}
quarkus.grpc.clients.ranking-service.port=${RANKING_SVC_PORT:9001}
quarkus.grpc.clients.ranking-service.plain-text=true

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=docs
quarkus.smallrye-openapi.path=openapi.yaml
quarkus.openapi.always-include=true


quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.console.color=true

quarkus.grpc.health.enabled=true