ranking-service-api/mp-rest/url=${RANKING_SERVICE_URL:http://localhost:8080}

quarkus.redis.hosts=${QUARKUS_REDIS_HOSTS:redis://localhost:6379}
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}

# Default Persistence Unit (Primary)
quarkus.hibernate-orm.packages=fc.ul.scrimfinder.domain
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
quarkus.hibernate-orm.schema-management.strategy=none

quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.locations=db/migration
quarkus.http.port=${HTTP_PORT:8080}
quarkus.http.root-path=/api/v1/matchmaking

quarkus.grpc.clients.player-service.host=${PLAYER_FILLING_SVC_HOST:detail-filling-service}
quarkus.grpc.clients.player-service.port=${PLAYER_FILLING_SVC_PORT:9000}
quarkus.grpc.clients.player-service.plain-text=true

quarkus.grpc.clients.ranking-service.host=${RANKING_SVC_HOST:ranking-service}
quarkus.grpc.clients.ranking-service.port=${RANKING_SVC_PORT:9001}
quarkus.grpc.clients.ranking-service.plain-text=true

rabbitmq-host=${RABBITMQ_HOST:rabbitmq}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USER:guest}
rabbitmq-password=${RABBITMQ_PASSWORD:guest}
mp.messaging.outgoing.match-results-events.connector=smallrye-rabbitmq
mp.messaging.outgoing.match-results-events.exchange.name=scrim.match-results
mp.messaging.outgoing.match-results-events.default-routing-key=match.results

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=docs
quarkus.smallrye-openapi.path=openapi.yaml
quarkus.openapi.always-include=true

quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
# Test profile configuration
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
