apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scrimfinder
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/SousaTrashBin/ScrimFinder.git"
      targetRevision: work/bruno
      path: k8s/charts/scrimfinder
      helm:
        releaseName: scrimfinder
        valueFiles:
          - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: scrimfinder
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false
  