ranking-service-api/mp-rest/url=${RANKING_SERVICE_URL:http://localhost:8081}

quarkus.redis.hosts=${REDIS_URL:redis://localhost:6379}
quarkus.datasource.db-kind=${DB_KIND:h2}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:h2:mem:matchmaking;DB_CLOSE_DELAY=-1}
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.http.port=${HTTP_PORT:8080}
