scrimfinder-external-api/mp-rest/url=${DETAIL_FILLING_SERVICE_URL:http://localhost:8081}
scrimfinder-match-history-api/mp-rest/url=${MATCH_HISTORY_SERVICE_URL:http://localhost:8082}

quarkus.datasource.db-kind=${DB_KIND:postgresql}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/ranking}
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.http.port=${HTTP_PORT:8080}
quarkus.http.root-path=/api/v1/ranking

quarkus.grpc.server.port=${GRPC_PORT:9001}

quarkus.grpc.clients.player-service.host=${PLAYER_FILLING_SERVICE_HOST:detail-filling-service}
quarkus.grpc.clients.player-service.port=${PLAYER_FILLING_SERVICE_PORT:9000}

quarkus.grpc.clients.history-service.host=${MATCH_HISTORY_SERVICE_HOST:match-history-service}
quarkus.grpc.clients.history-service.port=${MATCH_HISTORY_SERVICE_PORT:9002}

quarkus.swagger-ui.always-include=true
quarkus.openapi.always-include=true

quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.console.color=true

quarkus.grpc.health.enabled=true