# Root logger configuration - Sets the default minimum level for all loggers
quarkus.log.level=ALL
# On shutdown, allows the service to still answer to requests, but with a failing readiness probe (no more requests)
quarkus.shutdown.delay-enabled=true
quarkus.shutdown.delay=3000
quarkus.http.port=${HTTP_PORT}
config.riot-api/mp-rest/url=${RIOT_SERVICE_URL}