quarkus.log.level=INFO
quarkus.log.min-level=INFO
quarkus.shutdown.delay-enabled=true
quarkus.shutdown.delay=3000
quarkus.http.port=${HTTP_PORT:8080}
config.riot-api-key=${RIOT_API_KEY:default_value}
config.riot-api-region=europe
config.riot-api-subregion=EUW1
quarkus.rest-client.riot-match-api.url=${RIOT_MATCH_SERVICE_URL:http://localhost:8081}
