quarkus.log.level=ALL
quarkus.shutdown.delay-enabled=true
quarkus.shutdown.delay=3000
quarkus.http.port=${HTTP_PORT:8080}
config.riot-api=${RIOT_API_TOKEN:default_token}
quarkus.rest-client.riot-api.url=${RIOT_SERVICE_URL:http://localhost:8081}
