# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: training_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'training_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16training_service.proto\x12\x0bscrimfinder\"7\n\x13\x46orwardMatchRequest\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\"~\n\x14\x46orwardMatchResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07game_id\x18\x03 \x01(\t\x12\x10\n\x08\x64raft_ok\x18\x04 \x01(\x08\x12\x10\n\x08\x62uild_ok\x18\x05 \x01(\x08\x12\x0f\n\x07perf_ok\x18\x06 \x01(\x08\"(\n\x15GetActiveModelRequest\x12\x0f\n\x07\x63oncern\x18\x01 \x01(\t\"\xad\x01\n\x16GetActiveModelResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x10\n\x08model_id\x18\x02 \x01(\x05\x12\x0f\n\x07\x63oncern\x18\x03 \x01(\t\x12\x11\n\talgorithm\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\t\x12\x11\n\tfile_path\x18\x06 \x01(\t\x12\x14\n\x0cmetrics_json\x18\x07 \x01(\t\x12\x14\n\x0c\x61\x63tivated_at\x18\x08 \x01(\t\"\x14\n\x12HealthCheckRequest\"f\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0egames_ingested\x18\x03 \x01(\x05\x12\x15\n\ractive_models\x18\x04 \x03(\t2\x99\x02\n\x0fTrainingService\x12U\n\x0c\x46orwardMatch\x12 .scrimfinder.ForwardMatchRequest\x1a!.scrimfinder.ForwardMatchResponse\"\x00\x12[\n\x0eGetActiveModel\x12\".scrimfinder.GetActiveModelRequest\x1a#.scrimfinder.GetActiveModelResponse\"\x00\x12R\n\x0bHealthCheck\x12\x1f.scrimfinder.HealthCheckRequest\x1a .scrimfinder.HealthCheckResponse\"\x00\x42)\n\x16\x66\x63.ul.scrimfinder.grpcB\rAnalysisProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'training_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026fc.ul.scrimfinder.grpcB\rAnalysisProtoP\001'
  _globals['_FORWARDMATCHREQUEST']._serialized_start=39
  _globals['_FORWARDMATCHREQUEST']._serialized_end=94
  _globals['_FORWARDMATCHRESPONSE']._serialized_start=96
  _globals['_FORWARDMATCHRESPONSE']._serialized_end=222
  _globals['_GETACTIVEMODELREQUEST']._serialized_start=224
  _globals['_GETACTIVEMODELREQUEST']._serialized_end=264
  _globals['_GETACTIVEMODELRESPONSE']._serialized_start=267
  _globals['_GETACTIVEMODELRESPONSE']._serialized_end=440
  _globals['_HEALTHCHECKREQUEST']._serialized_start=442
  _globals['_HEALTHCHECKREQUEST']._serialized_end=462
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=464
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=566
  _globals['_TRAININGSERVICE']._serialized_start=569
  _globals['_TRAININGSERVICE']._serialized_end=850
# @@protoc_insertion_point(module_scope)
