CREATE TABLE IF NOT EXISTS queue (
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  mmr_rule_type VARCHAR(64) NOT NULL,
  initial_mmr INTEGER NOT NULL DEFAULT 1000,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS player (
  id UUID PRIMARY KEY,
  discord_username VARCHAR(255) NOT NULL UNIQUE,
  soloq_mmr INTEGER NOT NULL DEFAULT 1000,
  flex_mmr INTEGER NOT NULL DEFAULT 1000
);

CREATE TABLE IF NOT EXISTS riot_account (
  id UUID PRIMARY KEY,
  puuid VARCHAR(255) NOT NULL UNIQUE,
  game_name VARCHAR(255) NOT NULL,
  tag_line VARCHAR(255) NOT NULL,
  region VARCHAR(64) NOT NULL,
  player_id UUID NOT NULL REFERENCES player(id) ON DELETE CASCADE,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS player_ranking (
  id UUID PRIMARY KEY,
  queue_id UUID NOT NULL REFERENCES queue(id) ON DELETE CASCADE,
  player_id UUID NOT NULL REFERENCES player(id) ON DELETE CASCADE,
  mmr INTEGER NOT NULL,
  wins INTEGER NOT NULL DEFAULT 0,
  losses INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uq_player_ranking_player_queue UNIQUE (player_id, queue_id)
);
