[all:vars]
gcp_project=lookup('env', 'SCRIM_PROJECT_ID')
gcp_cred_kind=serviceaccount
gcp_cred_file=ansible-svc.json
zone=lookup('env', 'SCRIM_REGION')-a
region=lookup('env', 'SCRIM_REGION')
machine_type="e2-standard-4"
image="projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts"

[localhost]

[gce_instances_ips] # Filled in main task