apiVersion: apps/v1
kind: Deployment
metadata:
  name: detail-filling-service
  namespace: scrimfinder
  labels:
    app: detail-filling-service
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: detail-filling-service
  template:
    metadata:
      name: detail-filling-service-pod
      namespace: scrimfinder
      labels:
        app: detail-filling-service
    spec:
      containers:
        - name: detail-filling-service
          image: scrimfinder/detail-filling-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "16Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
      restartPolicy: Always
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: detail-filling-service-hpa
  namespace: scrimfinder
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: detail-filling-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: detail-filling-service-service
  namespace: scrimfinder
spec:
  selector:
    app: detail-filling-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
      