apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaking-service
  namespace: scrimfinder
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: matchmaking-service
  template:
    metadata:
      labels:
        app: matchmaking-service
    spec:
      containers:
        - name: matchmaking-service
          image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/matchmaking-service:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9000
              name: grpc
          envFrom:
            - configMapRef:
                name: matchmaking-service-config
            - secretRef:
                name: matchmaking-service-secrets
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /api/v1/matchmaking/q/health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/matchmaking/q/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: matchmaking-service-config
  namespace: scrimfinder
data:
  RANKING_SVC_HOST: "ranking-service"
  RANKING_SVC_PORT: "9001"
  PLAYER_FILLING_SVC_HOST: "detail-filling-service"
  PLAYER_FILLING_SVC_PORT: "8080"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: matchmaking-service-hpa
  namespace: scrimfinder
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: matchmaking-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: v1
kind: Service
metadata:
  name: matchmaking-service
  namespace: scrimfinder
spec:
  selector:
    app: matchmaking-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9000
      targetPort: 9000