apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-history-service
  namespace: scrimfinder
  labels:
    app: match-history-service
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: match-history-service
  template:
    metadata:
      name: match-history-service-pod
      namespace: scrimfinder
      labels:
        app: match-history-service
    spec:
      containers:
        - name: match-history-service
          image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/match-history-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /api/v1/history/q/health/live
              port: 8080
            failureThreshold: 2
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/history/q/health/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: match-history-service-config
            - secretRef:
                name: match-history-service-secrets
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: match-history-service-config
data:
  DB_KIND: "postgresql"
  DETAIL_FILLING_SERVICE_URL: "http://detail-filling-service:8080"
  TRAINING_SERVICE_HOST: "training-service"
  TRAINING_SERVICE_PORT: "8000"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: match-history-service-hpa
  namespace: scrimfinder
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: match-history-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: match-history-service-service
  namespace: scrimfinder
spec:
  selector:
    app: match-history-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
      