@baseUrl = http://match-history-service:8080/api/v1/history

@matchId1 = EUW1_7779779801
@matchId2 = EUW1_7798917216
@matchId3 = EUW1_7794855675
@matchId4 = EUW1_7799338678
@matchId5 = EUW1_7793513696
@matchId6 = EUW1_7797556115

###
# @name POST new match 1

POST {{baseUrl}}/matches/{{matchId1}}?queueId=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
Accept: application/json
Content-Type: application/json

{
    "4BSeyKZx1VPcsBDKK1HzMezhIrleBG7dJz0n7Hi3-O_8NdA8G8y3fmdfGKeXcH56ji33hV2wOWbBmw": 1,
    "MPusRAWjBIbyPNxfl_1XC5jd4vHCNWxIPCH07C2U1x_V0rxPzNOrJrZP6_0CaycLvQjmLar00wnKMQ": 2,
    "YGSCC506W3gP38oH5RVjg5huDFNN6arrllZAgKyYwe2LmKmJMv_y_cp1lekFDaOBvHzrklXUL14m8w": 3,
    "sgjC2z7p8LliY-9AuSedfanEi_Gt50slj_2UADPMyzRssffXQAbVWest4SxBsBAen4z_B1wKqPuADw": 4,
    "URrzCmHNvRCdKEIErjlfil1K0Q6ZXJMTJB0jQNge_LgmtLg7QeUix2WoOxBrhFtuj6c4J8XDQR__xg": 5,
    "SPVUcCh6z9xqvm98Kc63KdvLCUx0-FjvLBDRYL1J4r1eGYkkcosmxC_oPf3VbtYXhne1j0XDFOESRA": -1,
    "XVg0GIWPQ03YiBuIrx4lQC-FxXxsdGbfJ0-V5a-HHvDW-GbmJzwHk88-mOA5_pYLsa7FyBHYY54-nA": -2,
    "9xRZIOSM6G2fOOp_0hmptk1dm6IUIJ0PQXLMpDGztdQkgkWvlRJ-rQEKK9FidtF4yb1bXhIyBTZ74A": -3,
    "shwIFJrJiBlxqwuetxWj-kftHRLb2H2CPiqOeXtiOjKgDyB-b2tjpoY4L8MIf4plOvfGaEJTgg7o_w": -4,
    "wVVklCU3Zh5yS4SWetFU7Uevd2uWpiK183SmxCYp6aSk3k0AVlEV_nr5g6_haM3ks4WYZE2HJOs5zg": -5
}

###
# @name GET match 1

GET {{baseUrl}}/matches/{{matchId1}}
Accept: application/json
Content-Type: application/json

###
# @name Filter empty

GET {{baseUrl}}/matches?page=0&size=20

###
# @name Filter by queueId = aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
}

###
# @name Filter by queueId = baaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "baaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab"
}

###
# @name Filter by time >= 10000

GET {{baseUrl}}/matches?page=0&size=20

{
    "time": {
        "min": 10000
    }
}

### Above match is between 1773524078235 and 1773524079597 (inclusive)
# @name Filter by time >= 1773524078335

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524078335
    }
}

### Above match is between 1773524078235 and 1773524079597 (inclusive)
# @name Filter by time >= 1873524078235 (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1873524078235
    }
}

### Above match is between 1773524078235 and 1773524079597 (inclusive)
# @name Filter by time <= 1873524078235

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "max": 1873524078235
    }
}

### Above match is between 1773524078235 and 1773524079597 (inclusive)
# @name Filter by time <= 1673524078235 (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "max": 1673524078235
    }
}

### Above match is between 1773524078235 and 1773524079597 (inclusive)
# @name Filter by time = 1773524078235

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524078235,
        "max": 1773524078235
    }
}

### Above match is between 1773524078235 and 1773524079597 (inclusive)
# @name Filter by time = 1773524079597

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524079597,
        "max": 1773524079597
    }
}

### Above match is between 1773524078235 and 1773524079597 (inclusive)
# @name Filter by time = 1773524079598 (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524079598,
        "max": 1773524079598
    }
}

### Above match has champions: GNAR, VAYNE, ORIANNA, ASHE, SERAPHINE, JAYCE, QIYANA, AHRI, SENNA AND BLITZCRANK
# @name Filter by matches with champion GNAR

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524079597,
        "max": 1773524079597
    },
    "champions": [
        "GNAR"
    ]
}

### Above match has champions: GNAR, VAYNE, ORIANNA, ASHE, SERAPHINE, JAYCE, QIYANA, AHRI, SENNA AND BLITZCRANK
# @name Filter by matches with champion JINX (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524079597,
        "max": 1773524079597
    },
    "champions": [
        "JINX"
    ]
}

### Above match has champions: GNAR, VAYNE, ORIANNA, ASHE, SERAPHINE, JAYCE, QIYANA, AHRI, SENNA AND BLITZCRANK
# @name Filter by matches with champions GNAR and JINX (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524079597,
        "max": 1773524079597
    },
    "champions": [
        "GNAR",
        "JINX"
    ]
}

### Above match has champions: GNAR, VAYNE, ORIANNA, ASHE, SERAPHINE, JAYCE, QIYANA, AHRI, SENNA AND BLITZCRANK
# @name Filter by matches with champion ASHE and BLITZCRANK

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524079597,
        "max": 1773524079597
    },
    "champions": [
        "ASHE",
        "BLITZCRANK"
    ]
}

### Above match was made in patch 16.5
# @name Filter by matches made since patch 16.0

GET {{baseUrl}}/matches?page=0&size=20

{
    "patch": {
        "min": "16.0"
    }
}

### Above match was made in patch 16.5
# @name Filter by matches made since patch 16.6 (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "patch": {
        "min": "16.6"
    }
}

### Above match was made in patch 16.5
# @name Filter by matches made until patch 16.4 (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "patch": {
        "max": "16.4"
    }
}

### Above match was made in patch 16.5
# @name Filter by matches made until patch 16.5

GET {{baseUrl}}/matches?page=0&size=20

{
    "patch": {
        "max": "16.5"
    }
}

### Above match was made in patch 16.5
# @name Filter by matches made since patch 16.5.1 (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "patch": {
        "min": "16.5.1"
    }
}

### Above match was made in patch 16.5
# @name Filter by matches made between patches 16 and 16.3 (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "patch": {
        "min": "16",
        "max": "16.3"
    }
}

### Above match was made in patch 16.5
# @name Filter by matches made between patches 16 and 17.8

GET {{baseUrl}}/matches?page=0&size=20

{
    "patch": {
        "min": "16",
        "max": "17.8"
    }
}

###
# @name Filter by matches with some player having more than 5 kills

GET {{baseUrl}}/matches?page=0&size=20

{
    "players": [
        {
            "kills": {
                "min": 5
            }
        }
    ]
}

### Above match has players: Maynter, Fentasm, SlayderW, KISS OF DEATH, Last dance, baby kiin, J1HUIV, Yoriich1, KC NEXT ADKING, berebooo
# @name Filter by matches with player KISS OF DEATH

GET {{baseUrl}}/matches?page=0&size=20

{
    "players": [
        {
            "playerName": "KISS OF DEATH"
        }
    ]
}

###
# @name Filter by matches with player Maynter having role TOP

GET {{baseUrl}}/matches?page=0&size=20

{
    "players": [
        {
            "playerName": "Maynter",
            "role": "TOP"
        }
    ]
}

###
# @name Filter by matches with player Last dance having role SUPPORT on the blue team with less than 5000 healing and player berebooo winning with a single kill and more than 8000 gold

GET {{baseUrl}}/matches?page=0&size=20

{
    "players": [
        {
            "playerName": "Last dance",
            "role": "SUPPORT",
            "teamSide": "BLUE",
            "healing": {
                "max": 5000
            }
        },
        {
            "playerName": "berebooo",
            "won": true,
            "kills": {
                "min": 1,
                "max": 1
            },
            "gold": {
                "min": 8000
            }
        }
    ]
}

###
# @name Filter by matches where someone played as champion ASHE and player Fentasm played as one of the following champions: VAYNE, DIANA or JAX

GET {{baseUrl}}/matches?page=0&size=20

{
    "champions": [
        "ASHE"
    ],
    "players": [
        {
            "playerName": "Fentasm",
            "champions": [
                "VAYNE",
                "DIANA",
                "JAX"
            ]
        }
    ]
}

### Above match has team blue with 13 kills and team red with 35 kills
# @name Filter by matches where some team had at least 20 kills

GET {{baseUrl}}/matches?page=0&size=20

{
    "teams": [
        {
            "teamKills": {
                "min": 20
            }
        }
    ]
}

### Above match has team blue with 13 kills and team red with 35 kills
# @name Filter by matches where some team had at least 20 kills and team blue had at most 15 kills and between 30 and 40 deaths

GET {{baseUrl}}/matches?page=0&size=20

{
    "teams": [
        {
            "teamKills": {
                "min": 20
            }
        },
        {
            "teamSide": "BLUE",
            "teamKills": {
                "max": 15
            },
            "teamDeaths": {
                "min": 30,
                "max": 40
            }
        }
    ]
}

###
# @name Filter by matches that have a player on the blue team and a player that won on the red team

GET {{baseUrl}}/matches?page=0&size=20

{
    "players": [
        {
            "playerName": "Maynter",
            "teamSide": "BLUE",
            "won": false
        },
        {
            "playerName": "baby kiin",
            "teamSide": "RED",
            "won": true
        }
    ]
}

###
# @name Filter by everything from above match

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "patch": {
        "min": "16.5",
        "max": "16.5"
    },
    "time": {
        "min": 1773524078235,
        "max": 1773524079597
    },
    "champions": [
        "GNAR",
        "VAYNE",
        "ORIANNA",
        "ASHE",
        "SERAPHINE",
        "JAYCE",
        "QIYANA",
        "AHRI",
        "SENNA",
        "BLITZCRANK"
    ],
    "players": [
        {
            "puuid": "4BSeyKZx1VPcsBDKK1HzMezhIrleBG7dJz0n7Hi3-O_8NdA8G8y3fmdfGKeXcH56ji33hV2wOWbBmw",
            "playerName": "Maynter",
            "playerTag": "EUW",
            "summonerIcon": 1301,
            "summonerLevel": {
                "min": 787,
                "max": 787
            },
            "kills": {
                "min": 1,
                "max": 1
            },
            "deaths": {
                "min": 5,
                "max": 5
            },
            "assists": {
                "min": 1,
                "max": 1
            },
            "healing": {
                "min": 3776,
                "max": 3776
            },
            "damageToPlayers": {
                "min": 64721,
                "max": 64721
            },
            "wards": {
                "min": 7,
                "max": 7
            },
            "gold": {
                "min": 6451,
                "max": 6451
            },
            "role": "TOP",
            "champions": [
                "GNAR"
            ],
            "csPerMinute": {
                "min": 6.1,
                "max": 6.1
            },
            "killedMinions": {
                "min": 139,
                "max": 139
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "BLUE",
            "won": false
        },
        {
            "puuid": "MPusRAWjBIbyPNxfl_1XC5jd4vHCNWxIPCH07C2U1x_V0rxPzNOrJrZP6_0CaycLvQjmLar00wnKMQ",
            "playerName": "Fentasm",
            "playerTag": "FENT",
            "summonerIcon": 6278,
            "summonerLevel": {
                "min": 656,
                "max": 656
            },
            "kills": {
                "min": 1,
                "max": 1
            },
            "deaths": {
                "min": 7,
                "max": 7
            },
            "assists": {
                "min": 4,
                "max": 4
            },
            "healing": {
                "min": 5874,
                "max": 5874
            },
            "damageToPlayers": {
                "min": 142137,
                "max": 142137
            },
            "wards": {
                "min": 4,
                "max": 4
            },
            "gold": {
                "min": 8100,
                "max": 8100
            },
            "role": "JUNGLE",
            "champions": [
                "VAYNE"
            ],
            "csPerMinute": {
                "min": 1.5,
                "max": 1.5
            },
            "killedMinions": {
                "min": 33,
                "max": 33
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "BLUE",
            "won": false
        },
        {
            "puuid": "YGSCC506W3gP38oH5RVjg5huDFNN6arrllZAgKyYwe2LmKmJMv_y_cp1lekFDaOBvHzrklXUL14m8w",
            "playerName": "SlayderW",
            "playerTag": "EUWW",
            "summonerIcon": 28,
            "summonerLevel": {
                "min": 103,
                "max": 103
            },
            "kills": {
                "min": 4,
                "max": 4
            },
            "deaths": {
                "min": 5,
                "max": 5
            },
            "assists": {
                "min": 2,
                "max": 2
            },
            "healing": {
                "min": 759,
                "max": 759
            },
            "damageToPlayers": {
                "min": 122557,
                "max": 122557
            },
            "wards": {
                "min": 5,
                "max": 5
            },
            "gold": {
                "min": 9823,
                "max": 9823
            },
            "role": "MID",
            "champions": [
                "ORIANNA"
            ],
            "csPerMinute": {
                "min": 9.3,
                "max": 9.3
            },
            "killedMinions": {
                "min": 211,
                "max": 211
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "BLUE",
            "won": false
        },
        {
            "puuid": "sgjC2z7p8LliY-9AuSedfanEi_Gt50slj_2UADPMyzRssffXQAbVWest4SxBsBAen4z_B1wKqPuADw",
            "playerName": "KISS OF DEATH",
            "playerTag": "YEN",
            "summonerIcon": 1455,
            "summonerLevel": {
                "min": 476,
                "max": 476
            },
            "kills": {
                "min": 6,
                "max": 6
            },
            "deaths": {
                "min": 9,
                "max": 9
            },
            "assists": {
                "min": 4,
                "max": 4
            },
            "healing": {
                "min": 1315,
                "max": 1315
            },
            "damageToPlayers": {
                "min": 69636,
                "max": 69636
            },
            "wards": {
                "min": 7,
                "max": 7
            },
            "gold": {
                "min": 9597,
                "max": 9597
            },
            "role": "BOTTOM",
            "champions": [
                "ASHE"
            ],
            "csPerMinute": {
                "min": 6.4,
                "max": 6.4
            },
            "killedMinions": {
                "min": 146,
                "max": 146
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "BLUE",
            "won": false
        },
        {
            "puuid": "URrzCmHNvRCdKEIErjlfil1K0Q6ZXJMTJB0jQNge_LgmtLg7QeUix2WoOxBrhFtuj6c4J8XDQR__xg",
            "playerName": "Last dance",
            "playerTag": "Hexom",
            "summonerIcon": 1637,
            "summonerLevel": {
                "min": 106,
                "max": 106
            },
            "kills": {
                "min": 1,
                "max": 1
            },
            "deaths": {
                "min": 9,
                "max": 9
            },
            "assists": {
                "min": 8,
                "max": 8
            },
            "healing": {
                "min": 4690,
                "max": 4690
            },
            "damageToPlayers": {
                "min": 23399,
                "max": 23399
            },
            "wards": {
                "min": 24,
                "max": 24
            },
            "gold": {
                "min": 6350,
                "max": 6350
            },
            "role": "SUPPORT",
            "champions": [
                "SERAPHINE"
            ],
            "csPerMinute": {
                "min": 1.3,
                "max": 1.3
            },
            "killedMinions": {
                "min": 29,
                "max": 29
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "BLUE",
            "won": false
        },
        {
            "puuid": "SPVUcCh6z9xqvm98Kc63KdvLCUx0-FjvLBDRYL1J4r1eGYkkcosmxC_oPf3VbtYXhne1j0XDFOESRA",
            "playerName": "baby kiin",
            "playerTag": "keem",
            "summonerIcon": 6,
            "summonerLevel": {
                "min": 120,
                "max": 120
            },
            "kills": {
                "min": 5,
                "max": 5
            },
            "deaths": {
                "min": 3,
                "max": 3
            },
            "assists": {
                "min": 5,
                "max": 5
            },
            "healing": {
                "min": 2833,
                "max": 2833
            },
            "damageToPlayers": {
                "min": 144290,
                "max": 144290
            },
            "wards": {
                "min": 10,
                "max": 10
            },
            "gold": {
                "min": 11484,
                "max": 11484
            },
            "role": "TOP",
            "champions": [
                "JAYCE"
            ],
            "csPerMinute": {
                "min": 8.4,
                "max": 8.4
            },
            "killedMinions": {
                "min": 191,
                "max": 191
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "RED",
            "won": true
        },
        {
            "puuid": "XVg0GIWPQ03YiBuIrx4lQC-FxXxsdGbfJ0-V5a-HHvDW-GbmJzwHk88-mOA5_pYLsa7FyBHYY54-nA",
            "playerName": "J1HUIV",
            "playerTag": "000",
            "summonerIcon": 29,
            "summonerLevel": {
                "min": 445,
                "max": 445
            },
            "kills": {
                "min": 11,
                "max": 11
            },
            "deaths": {
                "min": 1,
                "max": 1
            },
            "assists": {
                "min": 6,
                "max": 6
            },
            "healing": {
                "min": 9874,
                "max": 9874
            },
            "damageToPlayers": {
                "min": 295508,
                "max": 295508
            },
            "wards": {
                "min": 4,
                "max": 4
            },
            "gold": {
                "min": 13424,
                "max": 13424
            },
            "role": "JUNGLE",
            "champions": [
                "QIYANA"
            ],
            "csPerMinute": {
                "min": 1.7,
                "max": 1.7
            },
            "killedMinions": {
                "min": 39,
                "max": 39
            },
            "tripleKills": {
                "min": 1,
                "max": 1
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "RED",
            "won": true
        },
        {
            "puuid": "9xRZIOSM6G2fOOp_0hmptk1dm6IUIJ0PQXLMpDGztdQkgkWvlRJ-rQEKK9FidtF4yb1bXhIyBTZ74A",
            "playerName": "Yoriichı",
            "playerTag": "EUW",
            "summonerIcon": 5045,
            "summonerLevel": {
                "min": 210,
                "max": 210
            },
            "kills": {
                "min": 5,
                "max": 5
            },
            "deaths": {
                "min": 1,
                "max": 1
            },
            "assists": {
                "min": 5,
                "max": 5
            },
            "healing": {
                "min": 6144,
                "max": 6144
            },
            "damageToPlayers": {
                "min": 140039,
                "max": 140039
            },
            "wards": {
                "min": 5,
                "max": 5
            },
            "gold": {
                "min": 10871,
                "max": 10871
            },
            "role": "MID",
            "champions": [
                "AHRI"
            ],
            "csPerMinute": {
                "min": 9.7,
                "max": 9.7
            },
            "killedMinions": {
                "min": 221,
                "max": 221
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "RED",
            "won": true
        },
        {
            "puuid": "shwIFJrJiBlxqwuetxWj-kftHRLb2H2CPiqOeXtiOjKgDyB-b2tjpoY4L8MIf4plOvfGaEJTgg7o_w",
            "playerName": "KC NEXT ADKING",
            "playerTag": "EUW",
            "summonerIcon": 29,
            "summonerLevel": {
                "min": 727,
                "max": 727
            },
            "kills": {
                "min": 13,
                "max": 13
            },
            "deaths": {
                "min": 3,
                "max": 3
            },
            "assists": {
                "min": 12,
                "max": 12
            },
            "healing": {
                "min": 12959,
                "max": 12959
            },
            "damageToPlayers": {
                "min": 110972,
                "max": 110972
            },
            "wards": {
                "min": 10,
                "max": 10
            },
            "gold": {
                "min": 13924,
                "max": 13924
            },
            "role": "BOTTOM",
            "champions": [
                "SENNA"
            ],
            "csPerMinute": {
                "min": 7.3,
                "max": 7.3
            },
            "killedMinions": {
                "min": 165,
                "max": 165
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "RED",
            "won": true
        },
        {
            "puuid": "wVVklCU3Zh5yS4SWetFU7Uevd2uWpiK183SmxCYp6aSk3k0AVlEV_nr5g6_haM3ks4WYZE2HJOs5zg",
            "playerName": "berebooo",
            "playerTag": "TR1",
            "summonerIcon": 3158,
            "summonerLevel": {
                "min": 346,
                "max": 346
            },
            "kills": {
                "min": 1,
                "max": 1
            },
            "deaths": {
                "min": 6,
                "max": 6
            },
            "assists": {
                "min": 26,
                "max": 26
            },
            "healing": {
                "min": 3544,
                "max": 3544
            },
            "damageToPlayers": {
                "min": 15953,
                "max": 15953
            },
            "wards": {
                "min": 33,
                "max": 33
            },
            "gold": {
                "min": 8253,
                "max": 8253
            },
            "role": "SUPPORT",
            "champions": [
                "BLITZCRANK"
            ],
            "csPerMinute": {
                "min": 0.7,
                "max": 0.7
            },
            "killedMinions": {
                "min": 15,
                "max": 15
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "RED",
            "won": true
        }
    ],
    "teams": [
        {
            "teamSide": "BLUE",
            "teamKills": {
                "min": 13,
                "max": 13
            },
            "teamDeaths": {
                "min": 35,
                "max": 35
            },
            "teamAssists": {
                "min": 19,
                "max": 19
            },
            "teamHealing": {
                "min": 16414,
                "max": 16414
            }
        },
        {
            "teamSide": "RED",
            "teamKills": {
                "min": 35,
                "max": 35
            },
            "teamDeaths": {
                "min": 14,
                "max": 14
            },
            "teamAssists": {
                "min": 54,
                "max": 54
            },
            "teamHealing": {
                "min": 35354,
                "max": 35354
            }
        }
    ]
}

###
# @name POST new match 2

POST {{baseUrl}}/matches/{{matchId2}}?queueId=bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb
Accept: application/json
Content-Type: application/json

{
    "thVeO_eCyKYUpDJvA4-vL5CflI3RysRcQwaIACUvuS-r26_IhEkBduKdo7YkZzDw_YTtSJYgMX0OMQ": 1,
    "mZFo4jj8Z55Fr6YouhRGwBwlvqY8YZ9eYz3ucrfahttilTRGsZcTam-XCfdJeBBOHjBUYe25qWUWkw": 2,
    "Ey0raHE0ykVGbRQaceL51IdGeK-QqsqytQx3BxDeQIB8heZu73SJEuH_SHlx2JuvJLA8EAEjhu211w": 3,
    "Fsei5NANQZ2k17UmtJLQ4fp8ATD4JUgkkvZCcA3kzF8RoYzubqdttGuemD2qSjoIhgeawv8jlcu28g": 4,
    "oQlou2goEFkGOZv5bmdyVBEpA3DsMz0qBalPDjrRhaHP_2lDgquhV_lcbPSjBWWuishBXZohTICe4g": 5,
    "2zxMCqgkiPY9-ToxJfC8lQNfcdJJcFt6XxLZYUf7KwcC7hBHHXz04T41yTPntrM8f6-uVdPUvvo_9g": -1,
    "psekYL5k_DUYLTgC6tMfGKMpe2nElXeiVexP-luCeoWgDro6I778EpYKVwvrhvkFiNpfOjSMnMbGow": -2,
    "NN5Nj3WKnMKziKatbnzzDj5lRhXkcoLKISevWncoGp3kI-GHtrhehrtXFZki7O1lkoO_nxQrbh0qOw": -3,
    "tWeE3feBAdIBz_U7FsRsQBtbdewejLa0WGK7KJN3NuqH-kxzKy4pp0FjCO04EqjZQzhGTRzMWA5iug": -4,
    "Tp1GfMn_PW3ed1hMQOLvQ8UGrslidkSaNKSn9oKJmOkgHVJ2hRCWPelcdm0tl8_f9L7H9oTlEPWpVA": -5
}

###
# @name POST new match 3

POST {{baseUrl}}/matches/{{matchId3}}?queueId=cccccccc-cccc-cccc-cccc-cccccccccccc
Accept: application/json
Content-Type: application/json

{
    "m94NvT3cCiwBAdkin_WieujGegevvdAMcATipKUKUjTMEbCjoFKOWaDZs4f-WZNFby7Emw8R3aXJTA": 1,
    "qN3mHmzgsn5x2OdU7wGTzF910PUAH17BCmhasCQTYKCr75A7rxsX9GsbU8Y0wxUltsnta0T4bXcBjA": 2,
    "-CCR1ff90zRImvo4uqICu6gi8fDuDrjX-bAZIXi0qootzpiDcLKNYs8vCuDBDIgwzTyKcdcAho4kCQ": 3,
    "NY6-gK_FV7Ntp0Heje7DB-W6At9Jo_ok8W1eAxgnSdxUjv9iwSFMGMHSALTpAH6uw6Kho66ZtjKdrw": 4,
    "LwHNklMmETZoGHhaAshP7sY1S8K1dtTfWv4_dnJijPE2msTSvjSUz-MyxEvjskqZrE2VUCcyT_eN5w": 5,
    "a6vWY8Vz_ghd0t5XVkMwZrv8mXSuJ9yymebB3ssbR-M_-j0T1d1Y8F48OrT1yb3zw4Nf3l0JPm5a_Q": -1,
    "DKjp2j9WEOyF8cu56OTWJ3PhpSmaAP0ufBU23vfPgNu32ZlwI0q9Xi9EdJrFmfHYuhDTpjNSt_PqdA": -2,
    "lc3w67a-sWXbAROqwCCpt8MDvwIsfJw73zPB_shMNMe3jVcfDWQuvsJOPEkQc5Oe0i247aFw81wmyA": -3,
    "ilD4eYx0K9kOfC5LF0PQHpS7Cdp0L3MiqL21t_omaZf6T_Ax9TFzG5vxp6aozcGGeUXfIT-NGsEXMQ": -4,
    "XqI4xrWyxVYt7GsdSx9yq0qx7uoqE-WwDEUMVClB2BMFxZiLnfje7qgrJJiE5dhHLemsi9NFcGOoWg": -5
}

###
# @name POST new match 4

POST {{baseUrl}}/matches/{{matchId4}}?queueId=dddddddd-dddd-dddd-dddd-dddddddddddd
Accept: application/json
Content-Type: application/json

{
    "LixBOV8cnGORF_Ef5y-Ohw8KCUwj6abGg9szFno9PTbhAOlHiCF0amiSjuI6fqwzu_sGUkzM1m538A": 1,
    "lSDy4VlOSbSJvAdUz581Rnw7_ES6YVarrmBrY2t6DJCgNqui-dalIWfBIo003cHwoFJXTlUCDAXlpg": 2,
    "46_lIp42f0fm2YnJDlhKcMdBNat_WPKi3LGyEVPvJpBtHM8SJ5_30UP_vrKhybH4-zufvmockXAofw": 3,
    "gVPtQnF9lLRDBgRsuegs8S_ZVVUf7SW-x40obzJyBHJzdMncZJtctT8FcEW-rxV7E0SHNWVgIFBkEQ": 4,
    "qBomfXVobQR4Q1lS0nifINlqKqFUxvKMTT8Nte421hgwuoDJ1gCTTEQM56ffCoC7g3LZ4feqm1eMNQ": 5,
    "GrWUPMmOPvmTZ4a8Keq2Wxejo3fXcSn404f1G00irKhMmnoBweDjAeZDG4LOJzcKZl-Lm3I5yaoBAw": -1,
    "qpUYk-DiZUnBe1OSCwDql0GxucCl-pcSdA_9O_AG8UG_2qW5AjK1c8FY_tUQ5ZhOJJkZWzCl2Wa_Wg": -2,
    "ISjAyJhS5-5-LW-eYCJ0o8AzCxAXqa4zb3kPhrn6i0_qWz89P-xEtkg56K0FYsMMqPWKl74zRJSHng": -3,
    "78tGwaWFxWG-p8W3H6_AzTIL9ZfCSowQ9p4VN5ziVEYE6wNxPHgDwcxg78lEoCr7CpgOUpu33DDHiQ": -4,
    "Cv_K7DESIanzCY739pEM9k24wSEMV5cgGcgYemnMwWvz5A_JTisfk8xYqVRvhVTD8Be4Y6nJvhC55A": -5
}

###
# @name POST new match 5

POST {{baseUrl}}/matches/{{matchId5}}?queueId=eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee
Accept: application/json
Content-Type: application/json

{
    "2zxMCqgkiPY9-ToxJfC8lQNfcdJJcFt6XxLZYUf7KwcC7hBHHXz04T41yTPntrM8f6-uVdPUvvo_9g": 1,
    "yDPO0g_pmn2BNBQC1l5NeogbIiY_6wUvb1KbJXb_fP8qena-NRIRUAUMOroEeTnJMdl2m-McclNQrw": 2,
    "zTiBSlGDzSE3UVVIySE9L26QQPgDMcgKl93gL1K5QNPtRDQsi1tCOtf2VtMMc4DCkNbV4MMVJGayCQ": 3,
    "qXNCYrjl5BMaK3GzUFr3gC0ZTkKaoLQuOwZNdtKfK9hK9vLzSRSM-AyPPc25Yz5MJWt-_zC5r5fp4w": 4,
    "dh4BtmUkAnOxbpZRpbZrY4aQtVXnUorWirjZzGc4xb7FP2FMyOA_unimKEXMDFLnHeOj5yJa_EelTQ": 5,
    "ygDlZMyLDYTcUIE68BqELjXP-gqMwIHt8-P5lzrzY4cx6EzoT3WqCS6d4YYh4XNMpHKzSROdFHyQ9A": -1,
    "TcYYHpM1YZIM6808-ghXE_2QZZVIaKtye5yjopcTpphOHeJFctFO0vnTJkxZbv2D5eQ2J1kbQdT-uQ": -2,
    "rasL4J3vPZNMGfAAkji-YmjrrtrYTBlwEezqakJNRTVo98ky6p1SukncKFSS1J5BtcvFoF4nVA8OHw": -3,
    "uu12xTQpHmW6rCDJsW6RbE1rHOaXpyN2f2sWyAGuFfvLiSF42rUVk6E_dpTiafI9rXenKuBWb7PFyw": -4,
    "CSmx0jhgfh6DK5nybS9e8GR5SIMkQNTWIEsFvSDeF3UXBpmaBf31Ed_iCXP-6c8OGS6PO6AAlz-qPA": -5
}

###
# @name POST new match 6

POST {{baseUrl}}/matches/{{matchId6}}?queueId=ffffffff-ffff-ffff-ffff-ffffffffffff
Accept: application/json
Content-Type: application/json

{
    "GrWUPMmOPvmTZ4a8Keq2Wxejo3fXcSn404f1G00irKhMmnoBweDjAeZDG4LOJzcKZl-Lm3I5yaoBAw": 1,
    "UOEBL22pJC3ovpP1bhCtEkW4iako8E_aa6cTXZHHRYN2NEDl3VIgaEWIDrsMv306y8vueYMtsPe3BQ": 2,
    "ikVBvFFGblqFGH2BeZ1ySuZbRGwBm0rKdGp7l-mQJWiTfGsYBxfmeO4ZeMCdrB4VTL6PkwjMKzxVgA": 3,
    "ByY8FqHZwsL9o1S_u-rL_nnCDZdVAhsa6YlwPbT97G1D7aQUiviAiWjZqsgnZC1-CS-g38V6eSnVFw": 4,
    "B4uKyKkz5h-FHdPSGdP1Vv-9IO5oxo-T40heOakfvAhRXKwQ7tgZqJI4SLN4j3I9OwYUw796onnUKA": 5,
    "2iYvTFZ2DTK2iKJq-9J92o8wuqCYCHA4OlRwvQrH0LqaCWPUEfmSi9E9bSmNTeef8wE6KgO5hb6Q-A": -1,
    "VZGoKvQzA4Zopno-oWojzOCOah3LWkrVhh4smfiRtLA8yDlPNHTNMofw-losbUBR69TQYqOhIgTmaA": -2,
    "B8SQ8-eqxoWtt1tNsJjz-w0aBFWpkUn9FHiHQjt1Op6wXIcuxk96a24KwdBFlSndq4Qta3q9AeqHZA": -3,
    "lO4rVnfIP_QOjzmCVRQYTZqxPFkpHuB4401C55JK240VuhaamwJNV_ADs-bHXhrMxcKTOeZryceP2Q": -4,
    "HpfRBs7ziG7Yipm138TBnYK4BCjKyM2Kl-mL2veXL5y7Lijsq59WfwSapLjMvM2zqgRHlINCNVWnow": -5
}

###
# @name Paging of all 6 matches - page 0, size 2

GET {{baseUrl}}/matches?page=0&size=2

###
# @name Paging of all 6 matches - page 1, size 2

GET {{baseUrl}}/matches?page=1&size=2

###
# @name Paging of all 6 matches - page 2, size 2

GET {{baseUrl}}/matches?page=2&size=2

###
# @name Paging of all 6 matches - page 3, size 2 (no match)

GET {{baseUrl}}/matches?page=3&size=2

###
# @name Paging of all 6 matches - page 0, size 5

GET {{baseUrl}}/matches?page=0&size=5

###
# @name Paging of all 6 matches - page 1, size 5

GET {{baseUrl}}/matches?page=1&size=5

###
# @name Paging of all 6 matches - page 2, size 5 (no match)

GET {{baseUrl}}/matches?page=2&size=5

###
# @name Sort all by queueId desc

GET {{baseUrl}}/matches?page=0&size=20

{
    "sortParams": [
        {
            "column": "QUEUE_ID",
            "direction": "DESC"
        }
    ]
}

###
# @name Sort all by time asc

GET {{baseUrl}}/matches?page=0&size=20

{
    "sortParams": [
        {
            "column": "TIME",
            "direction": "ASC"
        }
    ]
}

###
# @name Sort all by patch desc

GET {{baseUrl}}/matches?page=0&size=20

{
    "sortParams": [
        {
            "column": "PATCH",
            "direction": "DESC"
        }
    ]
}

###
# @name Sort all by patch desc, then blue team kills asc, then red healing (asc)

GET {{baseUrl}}/matches?page=0&size=20

{
    "sortParams": [
        {
            "column": "PATCH",
            "direction": "DESC"
        },
        {
            "column": "BLUE_KILLS",
            "direction": "ASC"
        },
        {
            "column": "RED_HEALING"
        }
    ]
}

###
# @name Filter by matches since patch 16.6 where someone played as KARTHUS; Sort all by patch desc, then blue team kills asc, then red healing desc; Get first 2 results
# (champions is inside players just to make this more complex since using the champions field outside match would also work)

GET {{baseUrl}}/matches?page=0&size=2

{
    "patch": {
        "min": 16.6
    },
    "players": [
        {
            "champions": [
                "KARTHUS"
            ]
        }
    ],
    "sortParams": [
        {
            "column": "PATCH",
            "direction": "DESC"
        },
        {
            "column": "BLUE_KILLS",
            "direction": "ASC"
        },
        {
            "column": "RED_HEALING",
            "direction": "DESC"
        }
    ]
}

###
# @name DELETE match 2

DELETE {{baseUrl}}/matches/{{matchId2}}
