# If running in the cloud, replace "match-history-service:8080" with EXTERNAL_IP
# obtained from the terminal after deploying or with "kubectl get svc scrimfinder-traefik -n scrimfinder"
@baseUrl = http://match-history-service:8080/api/v1/history

@matchId1 = EUW1_7779779801
@matchId2 = EUW1_7798917216
@matchId3 = EUW1_7794855675
@matchId4 = EUW1_7799338678
@matchId5 = EUW1_7793513696
@matchId6 = EUW1_7797556115

###
# @name POST new match 1

POST {{baseUrl}}/matches/{{matchId1}}?queueId=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
Accept: application/json
Content-Type: application/json

{
  "h_gAfdHVoI8vBJaIyyGOUqDJlXUGGePLUJdMpR1zoRVPdigrRKvMchFBAzIlOUpd4BLlr6Ba8BRSjw": 1,
  "OR5LGqOXhHVe8xj0IWrZHJWvOqLMVprQYTKbhawJQjzIFjDaFwCmnLc8Eid0rWTsZ6DRVCz65lsjrw": 2,
  "aqzT2pS2aQuBrkKv4izgg99_X73edM43rJoSbOhEhWg1lThgMB4yDcQsU8hGtXVTZnQmAYOawLMxeA": 3,
  "neqSH5XmjVkKkOki4MDq5Re0WwHMJ8BKsh_URZjThuWOINOoYvoe-YNU8Ll48ojGN5oCn4owcd2UQg": 4,
  "5GC_pKq053P0rngh7uTcjwB79V4vs1JoA3wzcUYgqlRr6tB-iNEF51CJnOQKrk4daGa5g8AdNezprw": 5,
  "Yhpm3VDVVQ09nAF9qUANOLFyItHikNj54vxB1yMzHmqIEohkIKEAeX-al94bBnYWtmsYv5CN6W3BvQ": -1,
  "avrrbs2xmpx-CjjNFWyRENlXRmLPTN4X-igl6r-I732hIPmTV_e5NlJ3W4qVJ58inDq4hY_6e5sqOA": -2,
  "CFcq57-yO1Shwn5cVI0nkIHWIGgzl-QV1g5qMAliHHZuFo_HBoX-S6ZjhidAKLenTr5ziJAHXxw-aQ": -3,
  "vyzwo-B74dAgHNsstNoWPioVU8bLh6kye-0xtdFTMQwM4Y-kCSZfwMpf29CadJJ1AvpYEPV5yNMicA": -4,
  "fwP-3K-Z_ghLAruQYlntd03YSdRCJeD7kaJQFujGJJpiwZ-ie9Rwkc9SmsiExqcnbnssXGmoAtyqHA": -5
}

###
# @name GET match 1

GET {{baseUrl}}/matches/{{matchId1}}
Accept: application/json
Content-Type: application/json

###
# @name Filter empty

GET {{baseUrl}}/matches?page=0&size=20

###
# @name Filter by queueId = aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
}

###
# @name Filter by queueId = baaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "baaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab"
}

###
# @name Filter by time >= 10000

GET {{baseUrl}}/matches?page=0&size=20

{
    "time": {
        "min": 10000
    }
}

### Above match is between 1773524078235 and 1773524079597 (inclusive)
# @name Filter by time >= 1773524078335

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524078335
    }
}

### Above match is between 1773524078235 and 1773524079597 (inclusive)
# @name Filter by time >= 1873524078235 (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1873524078235
    }
}

### Above match is between 1773524078235 and 1773524079597 (inclusive)
# @name Filter by time <= 1873524078235

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "max": 1873524078235
    }
}

### Above match is between 1773524078235 and 1773524079597 (inclusive)
# @name Filter by time <= 1673524078235 (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "max": 1673524078235
    }
}

### Above match is between 1773524078235 and 1773524079597 (inclusive)
# @name Filter by time = 1773524078235

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524078235,
        "max": 1773524078235
    }
}

### Above match is between 1773524078235 and 1773524079597 (inclusive)
# @name Filter by time = 1773524079597

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524079597,
        "max": 1773524079597
    }
}

### Above match is between 1773524078235 and 1773524079597 (inclusive)
# @name Filter by time = 1773524079598 (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524079598,
        "max": 1773524079598
    }
}

### Above match has champions: GNAR, VAYNE, ORIANNA, ASHE, SERAPHINE, JAYCE, QIYANA, AHRI, SENNA AND BLITZCRANK
# @name Filter by matches with champion GNAR

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524079597,
        "max": 1773524079597
    },
    "champions": [
        "GNAR"
    ]
}

### Above match has champions: GNAR, VAYNE, ORIANNA, ASHE, SERAPHINE, JAYCE, QIYANA, AHRI, SENNA AND BLITZCRANK
# @name Filter by matches with champion JINX (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524079597,
        "max": 1773524079597
    },
    "champions": [
        "JINX"
    ]
}

### Above match has champions: GNAR, VAYNE, ORIANNA, ASHE, SERAPHINE, JAYCE, QIYANA, AHRI, SENNA AND BLITZCRANK
# @name Filter by matches with champions GNAR and JINX (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524079597,
        "max": 1773524079597
    },
    "champions": [
        "GNAR",
        "JINX"
    ]
}

### Above match has champions: GNAR, VAYNE, ORIANNA, ASHE, SERAPHINE, JAYCE, QIYANA, AHRI, SENNA AND BLITZCRANK
# @name Filter by matches with champion ASHE and BLITZCRANK

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "time": {
        "min": 1773524079597,
        "max": 1773524079597
    },
    "champions": [
        "ASHE",
        "BLITZCRANK"
    ]
}

### Above match was made in patch 16.5
# @name Filter by matches made since patch 16.0

GET {{baseUrl}}/matches?page=0&size=20

{
    "patch": {
        "min": "16.0"
    }
}

### Above match was made in patch 16.5
# @name Filter by matches made since patch 16.6 (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "patch": {
        "min": "16.6"
    }
}

### Above match was made in patch 16.5
# @name Filter by matches made until patch 16.4 (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "patch": {
        "max": "16.4"
    }
}

### Above match was made in patch 16.5
# @name Filter by matches made until patch 16.5

GET {{baseUrl}}/matches?page=0&size=20

{
    "patch": {
        "max": "16.5"
    }
}

### Above match was made in patch 16.5
# @name Filter by matches made since patch 16.5.1 (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "patch": {
        "min": "16.5.1"
    }
}

### Above match was made in patch 16.5
# @name Filter by matches made between patches 16 and 16.3 (no match)

GET {{baseUrl}}/matches?page=0&size=20

{
    "patch": {
        "min": "16",
        "max": "16.3"
    }
}

### Above match was made in patch 16.5
# @name Filter by matches made between patches 16 and 17.8

GET {{baseUrl}}/matches?page=0&size=20

{
    "patch": {
        "min": "16",
        "max": "17.8"
    }
}

###
# @name Filter by matches with some player having more than 5 kills

GET {{baseUrl}}/matches?page=0&size=20

{
    "players": [
        {
            "kills": {
                "min": 5
            }
        }
    ]
}

### Above match has players: Maynter, Fentasm, SlayderW, KISS OF DEATH, Last dance, baby kiin, J1HUIV, Yoriich1, KC NEXT ADKING, berebooo
# @name Filter by matches with player KISS OF DEATH

GET {{baseUrl}}/matches?page=0&size=20

{
    "players": [
        {
            "playerName": "KISS OF DEATH"
        }
    ]
}

###
# @name Filter by matches with player Maynter having role TOP

GET {{baseUrl}}/matches?page=0&size=20

{
    "players": [
        {
            "playerName": "Maynter",
            "role": "TOP"
        }
    ]
}

###
# @name Filter by matches with player Last dance having role SUPPORT on the blue team with less than 5000 healing and player berebooo winning with a single kill and more than 8000 gold

GET {{baseUrl}}/matches?page=0&size=20

{
    "players": [
        {
            "playerName": "Last dance",
            "role": "SUPPORT",
            "teamSide": "BLUE",
            "healing": {
                "max": 5000
            }
        },
        {
            "playerName": "berebooo",
            "won": true,
            "kills": {
                "min": 1,
                "max": 1
            },
            "gold": {
                "min": 8000
            }
        }
    ]
}

###
# @name Filter by matches where someone played as champion ASHE and player Fentasm played as one of the following champions: VAYNE, DIANA or JAX

GET {{baseUrl}}/matches?page=0&size=20

{
    "champions": [
        "ASHE"
    ],
    "players": [
        {
            "playerName": "Fentasm",
            "champions": [
                "VAYNE",
                "DIANA",
                "JAX"
            ]
        }
    ]
}

### Above match has team blue with 13 kills and team red with 35 kills
# @name Filter by matches where some team had at least 20 kills

GET {{baseUrl}}/matches?page=0&size=20

{
    "teams": [
        {
            "teamKills": {
                "min": 20
            }
        }
    ]
}

### Above match has team blue with 13 kills and team red with 35 kills
# @name Filter by matches where some team had at least 20 kills and team blue had at most 15 kills and between 30 and 40 deaths

GET {{baseUrl}}/matches?page=0&size=20

{
    "teams": [
        {
            "teamKills": {
                "min": 20
            }
        },
        {
            "teamSide": "BLUE",
            "teamKills": {
                "max": 15
            },
            "teamDeaths": {
                "min": 30,
                "max": 40
            }
        }
    ]
}

###
# @name Filter by matches that have a player on the blue team and a player that won on the red team

GET {{baseUrl}}/matches?page=0&size=20

{
    "players": [
        {
            "playerName": "Maynter",
            "teamSide": "BLUE",
            "won": false
        },
        {
            "playerName": "baby kiin",
            "teamSide": "RED",
            "won": true
        }
    ]
}

###
# @name Filter by everything from above match

GET {{baseUrl}}/matches?page=0&size=20

{
    "queueId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "patch": {
        "min": "16.5",
        "max": "16.5"
    },
    "time": {
        "min": 1773524078235,
        "max": 1773524079597
    },
    "champions": [
        "GNAR",
        "VAYNE",
        "ORIANNA",
        "ASHE",
        "SERAPHINE",
        "JAYCE",
        "QIYANA",
        "AHRI",
        "SENNA",
        "BLITZCRANK"
    ],
    "players": [
        {
            "puuid": "h_gAfdHVoI8vBJaIyyGOUqDJlXUGGePLUJdMpR1zoRVPdigrRKvMchFBAzIlOUpd4BLlr6Ba8BRSjw",
            "playerName": "Maynter",
            "playerTag": "EUW",
            "summonerIcon": 1301,
            "summonerLevel": {
                "min": 787,
                "max": 787
            },
            "kills": {
                "min": 1,
                "max": 1
            },
            "deaths": {
                "min": 5,
                "max": 5
            },
            "assists": {
                "min": 1,
                "max": 1
            },
            "healing": {
                "min": 3776,
                "max": 3776
            },
            "damageToPlayers": {
                "min": 64721,
                "max": 64721
            },
            "wards": {
                "min": 7,
                "max": 7
            },
            "gold": {
                "min": 6451,
                "max": 6451
            },
            "role": "TOP",
            "champions": [
                "GNAR"
            ],
            "csPerMinute": {
                "min": 6.1,
                "max": 6.1
            },
            "killedMinions": {
                "min": 139,
                "max": 139
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "BLUE",
            "won": false
        },
        {
            "puuid": "OR5LGqOXhHVe8xj0IWrZHJWvOqLMVprQYTKbhawJQjzIFjDaFwCmnLc8Eid0rWTsZ6DRVCz65lsjrw",
            "playerName": "Fentasm",
            "playerTag": "FENT",
            "summonerIcon": 6278,
            "summonerLevel": {
                "min": 656,
                "max": 656
            },
            "kills": {
                "min": 1,
                "max": 1
            },
            "deaths": {
                "min": 7,
                "max": 7
            },
            "assists": {
                "min": 4,
                "max": 4
            },
            "healing": {
                "min": 5874,
                "max": 5874
            },
            "damageToPlayers": {
                "min": 142137,
                "max": 142137
            },
            "wards": {
                "min": 4,
                "max": 4
            },
            "gold": {
                "min": 8100,
                "max": 8100
            },
            "role": "JUNGLE",
            "champions": [
                "VAYNE"
            ],
            "csPerMinute": {
                "min": 1.5,
                "max": 1.5
            },
            "killedMinions": {
                "min": 33,
                "max": 33
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "BLUE",
            "won": false
        },
        {
            "puuid": "aqzT2pS2aQuBrkKv4izgg99_X73edM43rJoSbOhEhWg1lThgMB4yDcQsU8hGtXVTZnQmAYOawLMxeA",
            "playerName": "SlayderW",
            "playerTag": "EUWW",
            "summonerIcon": 28,
            "summonerLevel": {
                "min": 103,
                "max": 103
            },
            "kills": {
                "min": 4,
                "max": 4
            },
            "deaths": {
                "min": 5,
                "max": 5
            },
            "assists": {
                "min": 2,
                "max": 2
            },
            "healing": {
                "min": 759,
                "max": 759
            },
            "damageToPlayers": {
                "min": 122557,
                "max": 122557
            },
            "wards": {
                "min": 5,
                "max": 5
            },
            "gold": {
                "min": 9823,
                "max": 9823
            },
            "role": "MID",
            "champions": [
                "ORIANNA"
            ],
            "csPerMinute": {
                "min": 9.3,
                "max": 9.3
            },
            "killedMinions": {
                "min": 211,
                "max": 211
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "BLUE",
            "won": false
        },
        {
            "puuid": "neqSH5XmjVkKkOki4MDq5Re0WwHMJ8BKsh_URZjThuWOINOoYvoe-YNU8Ll48ojGN5oCn4owcd2UQg",
            "playerName": "KISS OF DEATH",
            "playerTag": "YEN",
            "summonerIcon": 1455,
            "summonerLevel": {
                "min": 476,
                "max": 476
            },
            "kills": {
                "min": 6,
                "max": 6
            },
            "deaths": {
                "min": 9,
                "max": 9
            },
            "assists": {
                "min": 4,
                "max": 4
            },
            "healing": {
                "min": 1315,
                "max": 1315
            },
            "damageToPlayers": {
                "min": 69636,
                "max": 69636
            },
            "wards": {
                "min": 7,
                "max": 7
            },
            "gold": {
                "min": 9597,
                "max": 9597
            },
            "role": "BOTTOM",
            "champions": [
                "ASHE"
            ],
            "csPerMinute": {
                "min": 6.4,
                "max": 6.4
            },
            "killedMinions": {
                "min": 146,
                "max": 146
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "BLUE",
            "won": false
        },
        {
            "puuid": "5GC_pKq053P0rngh7uTcjwB79V4vs1JoA3wzcUYgqlRr6tB-iNEF51CJnOQKrk4daGa5g8AdNezprw",
            "playerName": "Last dance",
            "playerTag": "Hexom",
            "summonerIcon": 1637,
            "summonerLevel": {
                "min": 106,
                "max": 106
            },
            "kills": {
                "min": 1,
                "max": 1
            },
            "deaths": {
                "min": 9,
                "max": 9
            },
            "assists": {
                "min": 8,
                "max": 8
            },
            "healing": {
                "min": 4690,
                "max": 4690
            },
            "damageToPlayers": {
                "min": 23399,
                "max": 23399
            },
            "wards": {
                "min": 24,
                "max": 24
            },
            "gold": {
                "min": 6350,
                "max": 6350
            },
            "role": "SUPPORT",
            "champions": [
                "SERAPHINE"
            ],
            "csPerMinute": {
                "min": 1.3,
                "max": 1.3
            },
            "killedMinions": {
                "min": 29,
                "max": 29
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "BLUE",
            "won": false
        },
        {
            "puuid": "Yhpm3VDVVQ09nAF9qUANOLFyItHikNj54vxB1yMzHmqIEohkIKEAeX-al94bBnYWtmsYv5CN6W3BvQ",
            "playerName": "baby kiin",
            "playerTag": "keem",
            "summonerIcon": 6,
            "summonerLevel": {
                "min": 120,
                "max": 120
            },
            "kills": {
                "min": 5,
                "max": 5
            },
            "deaths": {
                "min": 3,
                "max": 3
            },
            "assists": {
                "min": 5,
                "max": 5
            },
            "healing": {
                "min": 2833,
                "max": 2833
            },
            "damageToPlayers": {
                "min": 144290,
                "max": 144290
            },
            "wards": {
                "min": 10,
                "max": 10
            },
            "gold": {
                "min": 11484,
                "max": 11484
            },
            "role": "TOP",
            "champions": [
                "JAYCE"
            ],
            "csPerMinute": {
                "min": 8.4,
                "max": 8.4
            },
            "killedMinions": {
                "min": 191,
                "max": 191
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "RED",
            "won": true
        },
        {
            "puuid": "avrrbs2xmpx-CjjNFWyRENlXRmLPTN4X-igl6r-I732hIPmTV_e5NlJ3W4qVJ58inDq4hY_6e5sqOA",
            "playerName": "J1HUIV",
            "playerTag": "000",
            "summonerIcon": 29,
            "summonerLevel": {
                "min": 445,
                "max": 445
            },
            "kills": {
                "min": 11,
                "max": 11
            },
            "deaths": {
                "min": 1,
                "max": 1
            },
            "assists": {
                "min": 6,
                "max": 6
            },
            "healing": {
                "min": 9874,
                "max": 9874
            },
            "damageToPlayers": {
                "min": 295508,
                "max": 295508
            },
            "wards": {
                "min": 4,
                "max": 4
            },
            "gold": {
                "min": 13424,
                "max": 13424
            },
            "role": "JUNGLE",
            "champions": [
                "QIYANA"
            ],
            "csPerMinute": {
                "min": 1.7,
                "max": 1.7
            },
            "killedMinions": {
                "min": 39,
                "max": 39
            },
            "tripleKills": {
                "min": 1,
                "max": 1
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "RED",
            "won": true
        },
        {
            "puuid": "CFcq57-yO1Shwn5cVI0nkIHWIGgzl-QV1g5qMAliHHZuFo_HBoX-S6ZjhidAKLenTr5ziJAHXxw-aQ",
            "playerName": "Yoriichı",
            "playerTag": "EUW",
            "summonerIcon": 5045,
            "summonerLevel": {
                "min": 210,
                "max": 210
            },
            "kills": {
                "min": 5,
                "max": 5
            },
            "deaths": {
                "min": 1,
                "max": 1
            },
            "assists": {
                "min": 5,
                "max": 5
            },
            "healing": {
                "min": 6144,
                "max": 6144
            },
            "damageToPlayers": {
                "min": 140039,
                "max": 140039
            },
            "wards": {
                "min": 5,
                "max": 5
            },
            "gold": {
                "min": 10871,
                "max": 10871
            },
            "role": "MID",
            "champions": [
                "AHRI"
            ],
            "csPerMinute": {
                "min": 9.7,
                "max": 9.7
            },
            "killedMinions": {
                "min": 221,
                "max": 221
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "RED",
            "won": true
        },
        {
            "puuid": "vyzwo-B74dAgHNsstNoWPioVU8bLh6kye-0xtdFTMQwM4Y-kCSZfwMpf29CadJJ1AvpYEPV5yNMicA",
            "playerName": "KC NEXT ADKING",
            "playerTag": "EUW",
            "summonerIcon": 29,
            "summonerLevel": {
                "min": 727,
                "max": 727
            },
            "kills": {
                "min": 13,
                "max": 13
            },
            "deaths": {
                "min": 3,
                "max": 3
            },
            "assists": {
                "min": 12,
                "max": 12
            },
            "healing": {
                "min": 12959,
                "max": 12959
            },
            "damageToPlayers": {
                "min": 110972,
                "max": 110972
            },
            "wards": {
                "min": 10,
                "max": 10
            },
            "gold": {
                "min": 13924,
                "max": 13924
            },
            "role": "BOTTOM",
            "champions": [
                "SENNA"
            ],
            "csPerMinute": {
                "min": 7.3,
                "max": 7.3
            },
            "killedMinions": {
                "min": 165,
                "max": 165
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "RED",
            "won": true
        },
        {
            "puuid": "fwP-3K-Z_ghLAruQYlntd03YSdRCJeD7kaJQFujGJJpiwZ-ie9Rwkc9SmsiExqcnbnssXGmoAtyqHA",
            "playerName": "berebooo",
            "playerTag": "TR1",
            "summonerIcon": 3158,
            "summonerLevel": {
                "min": 346,
                "max": 346
            },
            "kills": {
                "min": 1,
                "max": 1
            },
            "deaths": {
                "min": 6,
                "max": 6
            },
            "assists": {
                "min": 26,
                "max": 26
            },
            "healing": {
                "min": 3544,
                "max": 3544
            },
            "damageToPlayers": {
                "min": 15953,
                "max": 15953
            },
            "wards": {
                "min": 33,
                "max": 33
            },
            "gold": {
                "min": 8253,
                "max": 8253
            },
            "role": "SUPPORT",
            "champions": [
                "BLITZCRANK"
            ],
            "csPerMinute": {
                "min": 0.7,
                "max": 0.7
            },
            "killedMinions": {
                "min": 15,
                "max": 15
            },
            "tripleKills": {
                "min": 0,
                "max": 0
            },
            "quadKills": {
                "min": 0,
                "max": 0
            },
            "pentaKills": {
                "min": 0,
                "max": 0
            },
            "teamSide": "RED",
            "won": true
        }
    ],
    "teams": [
        {
            "teamSide": "BLUE",
            "teamKills": {
                "min": 13,
                "max": 13
            },
            "teamDeaths": {
                "min": 35,
                "max": 35
            },
            "teamAssists": {
                "min": 19,
                "max": 19
            },
            "teamHealing": {
                "min": 16414,
                "max": 16414
            }
        },
        {
            "teamSide": "RED",
            "teamKills": {
                "min": 35,
                "max": 35
            },
            "teamDeaths": {
                "min": 14,
                "max": 14
            },
            "teamAssists": {
                "min": 54,
                "max": 54
            },
            "teamHealing": {
                "min": 35354,
                "max": 35354
            }
        }
    ]
}

###
# @name POST new match 2

POST {{baseUrl}}/matches/{{matchId2}}?queueId=bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb
Accept: application/json
Content-Type: application/json

{
  "18qWu0pwwA_sfCE8Ih_jIJhJiC7TlRK1dHXsKCZ_mFIAYPMf5-YQKH7gUFlDE9Fh-YZtYDsRMmySYg": 1,
  "M6xuDdkAxNyajMiFto9VTsdP_JTatZlz4xZ06sd-UzTHWuzcyKE23C0bR6zSKSmvR0mfvuciU-NFZQ": 2,
  "oM5fTuy-bSHFjW_CJJ5_nYolZ1WTFge_0_caldn2ylpUiJV6glA9RfmNDE35xHyakwejILdYMfBUOg": 3,
  "g9evN71NQIXfaQYH5ZdYMwZbEeg1wni_uiyQh__G0iD3bnz7yjHVA-Xi341gdhNpQ25hd58N1dth4w": 4,
  "yzV2y2SXD9LYlAiiJ8Rp3ehgDw5vSYHg-g1ai7ftYw4Ap2_Rz6fuKyyC-hh6ELcj-PwFueE4irOLDw": 5,
  "lCNhDWC2_gIx4v9nV8VsaBkLnUzwTCERUlP4WwQ5IwIE2gbv1MHkXkfjNs3Nm2tKXmmbM_I9TaNhIA": -1,
  "fyBU5HDdwtPD0bnPxU0Do7aDxT1voRiqyJH9m4m10R9E9Gkhx88TcY0AuWFNqLfefkw2xmQAIlpZXw": -2,
  "EIOzLS5LzdIUswGZu39ERMRucu0NOz4OzM3g4P1tkfxPA8jUHeO31DbkwOLddLzQABdwZ0Lx7qC9LQ": -3,
  "wg70K5vl52HTn_wvM15Ww62K_-xY9iHaV4L4Ua-_yRx-ApUosLJQdYrzIjHNCaz5O4UbIe-6griPwQ": -4,
  "k_-JlBGNZWdw8j9DFKrEJgdqF8DTrpAZxqyLnbObjq__klQIyvCNvdxl8wvJ2I5uvYnkfKSXnnOlEQ": -5
}

###
# @name POST new match 3

POST {{baseUrl}}/matches/{{matchId3}}?queueId=cccccccc-cccc-cccc-cccc-cccccccccccc
Accept: application/json
Content-Type: application/json

{
  "5E7p_JqqT7W1aOKnu7WYuH1dGbPNRbid4ABg5krfJkXHjzpmVVygMVT0dbNs9uhqUVwAXeqN4IlPvg": 1,
  "FXHewzL1Qc_ohCvjF5-8oL-hhFYbiFJgYp3np25Fbl2dIW0XZIQKWOQwOIgR0Am0_SA_-hdiIxn5_A": 2,
  "riiStkNjcgpVj6dS6fvreOzPbokiJ-vdd9sItppVpOAewmDtzDZgMSBavPNyAOHLzLjES2GFIeylUg": 3,
  "0-KnEtK_7SVO4lpjwdlDlXf9mNpC9oOQHH2L2V9gDYZ-guKX8yE_YsEtUhRAKe2pLpw8NXnAHegthw": 4,
  "MyHQYEb0U8_1qmHxTLQZ9c47YwifoGxyj2kzRVVtRt40E0KRIlOHOJlOeyTdxh9f9r1IYAoztW_-ag": 5,
  "KPFCfzlx1lKtR1RdZH1JlJY00A8420zRZsabdV2B64y9DgvzJWVPrNAdrGGbYnieeZuMYAeZ1bVT-Q": -1,
  "HmXlSkuKB3gO9i89eLzae1nEExIqpMKM-0MFvKZTglDCL1zGSBy5tmUDgMwblux7Ce3OtYUSFLFRwA": -2,
  "jDdkGffAD6n9C9UROGsq69kvDrigAZ3LCSSSgzz_n8irazwMImQKaWt8etMd0mZshzwx3qIAEK3J3A": -3,
  "pwkj6Ot3-0PnI0o8hw6bMr5uZsgJqEI-RiiznQ8mk_MAwa-DsNO9IvHuhcKmTikFm4QQQY-7ALdQoQ": -4,
  "W-3DEOys7ywiET2pB1M1qz4ajS5W0OmrhoohqL7vkbHQXC6fWRgJQHqWGaEArllx-g61roN6poreWA": -5
}

###
# @name POST new match 4

POST {{baseUrl}}/matches/{{matchId4}}?queueId=dddddddd-dddd-dddd-dddd-dddddddddddd
Accept: application/json
Content-Type: application/json

{
  "H9z5C7_1z1JV1DcjJCeYS1jqP6aZsZmbuZXlwbTU4f4rVVxGx1_0SyVofczHDrs8-cR1ZOpnlLLuRw": 1,
  "NM1lPAuV42p4e_ayTS7En7H1pcERAm2144Wjz3AOyVUNf2qpDg9Yqqw-gSE-qZazK_LiV84gt5AMxA": 2,
  "MSmob13-gteUOd4i2UHs2bE-mmNtEWlEd9op0-4-KFp66rt6Nk5-RgHbG_786O2baBtrpe8l_FYswQ": 3,
  "r-UtKl25xlZWPLFE9rOhgoVYRAwII6Z0-r_gM1jlQLWCS44Aof3LqhU5KprO1xQVMq469xjd2f6uxw": 4,
  "l2FBWF94RzmPdrOHt09OHh0sTfM6NArx8qz-Lny0gTo29LGEyyEaUSNcpCOYWf9ijUKEqsuE1QKUqg": 5,
  "qKOMfyHJBgAOZWRvs40ApYV2y3lgArCeH4VeMa-WIN9hcK_H8NumTYiuzP72IaOj4saKG1QBrAlDxw": -1,
  "_6rjNz3FaTcgsqyyIOQUXOuYaalxnQCigDUTRKVpS8QRjlu5LKSGRdTkMS_BUl914xQVq-VSytGlcQ": -2,
  "IniPcBDVgeXKZYvL6JmZxZFurTxtvqFPv1o2ALEb_xmphZwvADSqbsEZBp-qP4xEQRQCzCkwkMMJWw": -3,
  "XgUK4qSqT-xH4DSAHZ9iv4dBCpvFEYeRPudIIM_S9A7Qy94aQ5-25pdGsFZ7oARQOs6Pj1as9CF5ow": -4,
  "JW96X64srYdJ33XC7VvqStymmx5sV8Kb8ilFHfvRGjsHevHvrHfX8qfC4G0uuOipe7Lrf8AHX4uNoA": -5
}

###
# @name POST new match 5

POST {{baseUrl}}/matches/{{matchId5}}?queueId=eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee
Accept: application/json
Content-Type: application/json

{
  "lCNhDWC2_gIx4v9nV8VsaBkLnUzwTCERUlP4WwQ5IwIE2gbv1MHkXkfjNs3Nm2tKXmmbM_I9TaNhIA": 1,
  "8vrRcQyCJn6LGmhXNSzmAy9zvkjbFkvn1iKnpRJPAewveKxTaj4eBmbsCqxUHv2XyDZMvDn6eNzGnA": 2,
  "jcq6WfnAHdbaesDL2wNlnz7Pf1n-r9E2p3AGWkXYFPgfWZZdOFPVZ8lsNtwG7zaQK7fBAe3xErwFkA": 3,
  "elLhywUkyGm7kVBjzb6_vmeMEFFFmGxGZJLog7pCbGic9bKr6tt3mmvJkMw2_IsUgMWoftFDP0boFg": 4,
  "ucwTGFXRLW2MHxKymdTActhaeahSQEgvPjwHDxFZDHA3oLHuobceR3rb5jbtCMwBHhHPbSiWpe410g": 5,
  "E2y0tseFHqQf9h0mvZK3EmGIRex0mBwg3Ie3dODbKkC_rUnVfd0cZD72GgKVxUayyg1VHS02_gK1Mw": -1,
  "-Hl3VKQQiUgXxMjjFtXJZTYzo7GYelq6At2VoDDGQuMBse0rHv8EZlKVWWhKxSyK4XI3ktklqX7Iew": -2,
  "FywfM_4A01Fc9fOPVjH-yCn4bJqCCazxSX-KhIXVsYvVfxo-SSwhM_Nnh4ZFPPib6wekoWtGmNc2Jg": -3,
  "AZS7I30m0qwORmgCZpUk1zjvdQTfAPqT_YPp1Zeb1xCd5Ez6l7w92epN0_TPY4-ORZmoQFb90aeyOA": -4,
  "ikFLUSJnevSBwYwxvRK5j5deFvxy3fwUb49DsGT5mL8prQvQhbVdbdkbpuKhfwKfSEYXKnhpF3aGCA": -5
}

###
# @name POST new match 6

POST {{baseUrl}}/matches/{{matchId6}}?queueId=ffffffff-ffff-ffff-ffff-ffffffffffff
Accept: application/json
Content-Type: application/json

{
  "qKOMfyHJBgAOZWRvs40ApYV2y3lgArCeH4VeMa-WIN9hcK_H8NumTYiuzP72IaOj4saKG1QBrAlDxw": 1,
  "ORQJ9Nl_PPBFOFy6-4rYooTcqTE1IJGZSWTibusyjOZlbv-XIqXk3j8jqa7YvYgeQaJ6twAuDihA9Q": 2,
  "o4mHKpjFmbTP9MUMgvM0w4kvwJFnMQkOZszQYFmijusyPF-WgMBUOjlTNa253QY-IuCIjgkfrp4pIw": 3,
  "TptB7mos6JEnqSLtm_eQughecaZcoeKZkEc9uHkD9isJS1seFyRWm7exfq7JnYmerM6Oc4qM-E06Eg": 4,
  "x2M03HfPHjz7cFjZlhOaRhCT6MX2qz3PWWaFClNE13fyYdBCaA-xq57HSTRb1U-WD9_yuebDwT84WA": 5,
  "vmXJQtyV0g69x0dHKtRGUuKC4qUvRDxYiYyIc64tZoiLdeVzhqcYxOafQxxScEMqv8fDWDaxTMzW5Q": -1,
  "NA2q5TvqkNjNxjkb7Q17KgsqN9SjkjJMjwtqdESTfvXsq2j3jMZrWGtJNkBNEbdb7i5aB3CEbWrTEg": -2,
  "KY8Vnhc3AKs5asLwoAZVFww6UimGSN6pogZjirsk6MxLhpjrYhKv4TksRTalJqFiul0rX4ZXstvNgw": -3,
  "4u6EAsYgAyNRwQ3SJ09BHLjBPxYJCi8W_W27A71X_1j-PZoj83JDGRB-DqTjYjDfdhGgHB8b3cw2DA": -4,
  "jGhAx8Xc4_fNKQccCxFbwJFBbFNbplzOuhZD_3WUbZ1RXfcR6b9rgTUlJAD_FB2x0xR7hBdqc4GY5g": -5
}

###
# @name Paging of all 6 matches - page 0, size 2

GET {{baseUrl}}/matches?page=0&size=2

###
# @name Paging of all 6 matches - page 1, size 2

GET {{baseUrl}}/matches?page=1&size=2

###
# @name Paging of all 6 matches - page 2, size 2

GET {{baseUrl}}/matches?page=2&size=2

###
# @name Paging of all 6 matches - page 3, size 2 (no match)

GET {{baseUrl}}/matches?page=3&size=2

###
# @name Paging of all 6 matches - page 0, size 5

GET {{baseUrl}}/matches?page=0&size=5

###
# @name Paging of all 6 matches - page 1, size 5

GET {{baseUrl}}/matches?page=1&size=5

###
# @name Paging of all 6 matches - page 2, size 5 (no match)

GET {{baseUrl}}/matches?page=2&size=5

###
# @name Sort all by queueId desc

GET {{baseUrl}}/matches?page=0&size=20

{
    "sortParams": [
        {
            "column": "QUEUE_ID",
            "direction": "DESC"
        }
    ]
}

###
# @name Sort all by time asc

GET {{baseUrl}}/matches?page=0&size=20

{
    "sortParams": [
        {
            "column": "TIME",
            "direction": "ASC"
        }
    ]
}

###
# @name Sort all by patch desc

GET {{baseUrl}}/matches?page=0&size=20

{
    "sortParams": [
        {
            "column": "PATCH",
            "direction": "DESC"
        }
    ]
}

###
# @name Sort all by patch desc, then blue team kills asc, then red healing (asc)

GET {{baseUrl}}/matches?page=0&size=20

{
    "sortParams": [
        {
            "column": "PATCH",
            "direction": "DESC"
        },
        {
            "column": "BLUE_KILLS",
            "direction": "ASC"
        },
        {
            "column": "RED_HEALING"
        }
    ]
}

###
# @name Filter by matches since patch 16.6 where someone played as KARTHUS; Sort all by patch desc, then blue team kills asc, then red healing desc; Get first 2 results
# (champions is inside players just to make this more complex since using the champions field outside match would also work)

GET {{baseUrl}}/matches?page=0&size=2

{
    "patch": {
        "min": 16.6
    },
    "players": [
        {
            "champions": [
                "KARTHUS"
            ]
        }
    ],
    "sortParams": [
        {
            "column": "PATCH",
            "direction": "DESC"
        },
        {
            "column": "BLUE_KILLS",
            "direction": "ASC"
        },
        {
            "column": "RED_HEALING",
            "direction": "DESC"
        }
    ]
}

###
# @name DELETE match 2

DELETE {{baseUrl}}/matches/{{matchId2}}
